version: 2.1
orbs:
  python: circleci/python@1.0.0
jobs:
  build:
    docker:
      - image: circleci/python:3.8
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - run:
          name: show test result
          command: |
            echo Hello World
